SEASONS = {
    'PRESEASON3': 0,
    'SEASON3': 1,
    'PRESEASON2014': 2,
    'SEASON2014': 3,
    'PRESEASON2015': 4,
    'SEASON2015': 5,
    'PRESEASON2016': 6,
    'SEASON2016': 7,
    'PRESEASON2017': 8,
    'SEASON2017': 9
}

MATCHMAKING_QUEUES_SIMPLE = {
    0: 'Custom',
    2: 'Normal 5v5',
    4: 'Ranked solo 5v5',
    6: "Ranked premade 5v5",
    7: "Coop vs AI",
    8: "Normal 3v3",
    9: "Ranked flex 3v3",
    14: "Normal 5v5",
    16: "Dominion",
    17: "Dominion",
    25: "Dominion Coop vs AI",
    31: "Coop vs AI intro",
    32: "Coop vs AI beginner",
    33: "Coop vs AI intermediate",
    41: "Ranked team 3v3",
    42: "Ranked team 5v5",
    52: "Coop vs AI 3v3",
    61: "Teambuilder",
    65: "ARAM",
    70: "One for All",
    72: "Snowdown Showdown 1v1",
    73: "Snowdown Showdown 2v2",
    75: "Hexakill",
    76: "URF",
    78: "One for All Mirror",
    83: "URF vs AI",
    91: "Doom Bots I",
    92: "Doom Bots II",
    93: "Doom Bots V",
    96: "Ascension",
    98: "Hexakill TT",
    100: "Butcher's Bridge",
    300: "King Poro",
    310: "Nemesis",
    313: "Black Market Brawlers",
    315: "Nexus Siege",
    317: "Definitely Not Dominion",
    318: "ARURF",
    325: "All Random SR",
    400: "Normal 5v5",
    410: "Ranked 5v5",
    420: "Ranked 5v5 solo",
    430: "Normal 5v5 flex",
    440: "Ranked 5v5 flex",
    450: "ARAM",
    460: "Normal 3v3",
    470: "Ranked 3v3 flex",
    600: "Blood Hunt Assassin",
    610: "Dark Star",
    800: "TT Coop vs AI intermediate",
    810: "TT Coop vs AI intro",
    820: "TT Coop vs AI beginner",
    830: "SR Coop vs AI intro",
    840: "SR Coop vs AI beginner",
    850: "SR Coop vs AI intermediate",
    980: "Star Guardian Invasion: normal",
    990: "Star Guardian Invasion: onslaught"
}

MATCHMAKING_QUEUES = {
    0: 'Custom',
    2: 'Normal 5v5 blind pick',
    4: 'Ranked solo 5v5',
    6: 'Ranked premade 5v5',
    7: 'Historical coop vs ai',
    8: 'Normal 3v3',
    9: 'Ranked flex/premade 3v3',
    14: 'Normal 5v5 draft pick',
    16: 'Dominion 5v5 blind pick',
    17: 'Dominion 5v5 draft pick',
    25: 'Dominion Coop vs AI',
    31: 'Coop vs AI intro bot',
    32: 'Coop vs AI beginner bot',
    33: 'Historical Coop vs AI intermediate bot',
    41: 'Ranked team 3v3',
    42: 'Ranked team 5v5',
    52: 'Twisted treeline Coop vs AI',
    61: 'Team builder',
    65: 'ARAM',
    70: 'One for All',
    72: 'Snowdown showdown 1v1',
    73: 'Snowdown showdown 2v2',
    75: "Summoner's Rift 6x6 Hexakill",
    76: "URF",
    78: "One for All (Mirror)",
    83: "URF vs AI",
    91: "Doom bots rank 1",
    92: "Doom bots rank 2",
    93: "Doom bots rank 5",
    96: "Ascension",
    98: "Twisted Treeline 6x6 Hexakill",
    100: "Butcher's Bridge",
    300: "King Poro",
    310: "Nemesis",
    313: "Black Market Brawlers",
    315: "Nexus Siege",
    317: "Definitely Not Dominion",
    318: "ARURF",
    325: "All Random Summoner's Rift",
    400: "Normal 5v5 draft pick Summoner's Rift",
    410: "Ranked 5v5 draft pick Summoner's Rift",
    420: "Ranked 5v5 solo team builder",
    430: "Normal 5v5 blind pick Summoner's Rift",
    440: "Ranked 5v5 flex Summoner's Rift",
    450: "ARAM",
    460: "Normal 3v3 blind pick Twisted Treeline",
    470: "Ranked 3v3 flex Twisted Treeline",
    600: "Blood Hunt Assassin",
    610: "Dark Star",
    800: "Twisted Treeline Coop vs AI intermediate bot",
    810: "Twisted Treeline Coop vs AI intro bot",
    820: "Twisted Treeline Coop vs AI beginner bot",
    830: "Summoner's Rift Coop vs AI intro bot",
    840: "Summoner's Rift Coop vs AI beginner bot",
    850: "Summoner's Rift Coop vs AI intermediate bot",
    980: "Star Guardian Invasion: normal",
    990: "Star Guardian Invasion: onslaught"
}
    
GAMEMODES = {
    'CLASSIC': 'Classic',
    'ODIN': 'Dominion',
    'ARAM': 'ARAM',
    'TUTORIAL': 'Tutorial',
    'ONEFORALL': 'One for All',
    'ASCENSION': 'Ascension',
    'FIRSTBLOOD': 'Snowdown Showdown',
    'KINGPORO': 'King Poro',
    'SIEGE': 'Nexus Siege',
    'ASSASSINATE': 'Blood Hunt Assassin',
    'ASRS': 'ARAM SR',
    'DARKSTAR': 'Darkstar',
    'STARGUARDIAN': 'Star Guardian Invasion',
    'URF': 'URF',
    'DOOMBOTSTEEMO': 'Doombots Teemo'
}
